#!/usr/bin/env bash
#
# Refreshes the Cloudflare address ranges Nginx trusts.
#
#   sudo deploy/scripts/update-cloudflare-ips.sh && sudo systemctl reload nginx
#
# Cloudflare adds ranges from time to time. A range missing from the list is not
# a security hole — a request from it simply keeps Cloudflare's address instead
# of the visitor's — but it does mean those visitors all share one rate-limit
# bucket and appear identically in the logs.
#
# Writes the file only if both downloads succeeded and produced something that
# looks like a list of networks, so a captive portal or a failed request cannot
# replace a working config with an empty one.
set -euo pipefail

TARGET="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../nginx" && pwd)/cloudflare-real-ip.conf}"
TEMP="$(mktemp)"
trap 'rm -f "${TEMP}"' EXIT

V4="$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)"
V6="$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)"

# A sanity floor rather than an exact count: the published lists are around 15
# and 7 entries, and anything far short of that is a failed download.
if [[ "$(echo "${V4}" | grep -c '/')" -lt 5 || "$(echo "${V6}" | grep -c '/')" -lt 3 ]]; then
  echo "The downloaded ranges do not look right; ${TARGET} was left alone." >&2
  exit 1
fi

{
  echo "##"
  echo "# Cloudflare's address ranges, so Nginx can tell where a request really"
  echo "# came from. Generated by deploy/scripts/update-cloudflare-ips.sh on"
  echo "# $(date -u +%F). Do not edit by hand."
  echo "#"
  echo "# Trusting only these is what makes CF-Connecting-IP safe to believe: a"
  echo "# request from anywhere else has the header ignored."
  echo "##"
  echo
  echo "${V4}" | sed 's/^/set_real_ip_from /; s/$/;/'
  echo
  echo "${V6}" | sed 's/^/set_real_ip_from /; s/$/;/'
  echo
  echo "real_ip_header CF-Connecting-IP;"
} > "${TEMP}"

cp "${TEMP}" "${TARGET}"
echo "Wrote ${TARGET} ($(grep -c set_real_ip_from "${TARGET}") ranges)."
echo "Now: sudo nginx -t && sudo systemctl reload nginx"
